### ISSUE TITLE
No module named 'settrie' when calling the method of solve_mpqp

### ISSUE THREAD

**Issue by TimberJ99** [TAMUparametric/PPOPT#12]
In the source code of ppopt.mp_solvers.solve_mpqp, there is `From settrie import SetTrie` at the top, but there is no such a package in the network, surly 'pip install' fails to work. 

I know the author want to create a trie, but there is a package missing. Pls fix this bug, thanks a lot!

**Comment by DKenefake** [comment]
Hello, 

Thank you for pointing this out. I have looked into it and I think the most likely think that happened is that you didn't install the extra dependency as shown in the installation instructions. Please try with the following `pip` install command.

```
pip install -e git+https://github.com/mmihaltz/pysettrie.git#egg=pysettrie
```

**Comment by TimberJ99** [comment]
> Hello,
> 
> Thank you for pointing this out. I have looked into it and I think the most likely think that happened is that you didn't install the extra dependency as shown in the installation instructions. Please try with the following `pip` install command.
> 
> ```
> pip install -e git+https://github.com/mmihaltz/pysettrie.git#egg=pysettrie
> ```

Thank you for your reply! I noticed that you have pointed out this installation way in readme! And I found another problem when using the package, and I think it is crucial. Could you please fix that as well? See it in my newest issue, thank you!!
