### ISSUE TITLE
Problem with process_constraints()

### ISSUE THREAD

**Issue by TimberJ99** [TAMUparametric/PPOPT#13]
Thank you for your excellent work! I noticed that there is a crucial problem when using the method `process_constraints()`.

I understand that you use the method `process_constraints()` to transform a `MPLP_Program` object into an easy-solved one. However, using this method on the MPLP_Program object, after the mpLP is solved using one solver in your package and getting the `ppopt.solution.Solution` object, if I want to call `evaluate()` or `evaluate_objective()` on the solution object to retrieve the optimal solution or value of the original mpLP, it will return a wrong answer. If I change the preprocessing method from `process_constraints()` into `scale_constraints()` before solving, the return of  `evaluate()` or `evaluate_objective()` is correct. So I think you miss to deal with the solution retrieve process, i.e. getting the solution from the transformed mpLP instead of the original one. Could you fix this problem? I think this is very crucial because most of us want to get back the optimal solution according to the input of parameters.

@DKenefake

**Comment by DKenefake** [comment]
Ahh this seems like an issue, thank you for bringing it to my attention!

Could you please provide a minimal reproducible example? That would greatly speed up the bug hunting process.

**Comment by DKenefake** [comment]
I found where the error was coming from and patched it in the main branch. I will push it out onto pypi soon.  Thank you for bringing this to me!
