### ISSUE TITLE
Problems with MPQP solution

### ISSUE THREAD

**Issue by TimberJ99** [TAMUparametric/PPOPT#19]
Thank you for your excellent work again! A few months ago I noticed a  problem when using the method process_constraints(). Your following update soon fixed the bug, and I really appreciate it!
These months I kept using ppopt but all focused on MPLP. However, today I change my model into MPQP, and I noticed that ppopt generates wrong critical regions on my model. I have checked the code and some codes of your package, but no mistake was found. So I guess there are some bugs when soving MPQP.
Here is the model that I put into ppoot. The following latex code was generated by your method: `prog.latex()`
```
0: $$\min_{x} \frac{1}{2}\left[\begin{matrix}x_0\\x_1\\x_2\\x_3\end{matrix}\right]^{T}\left[\begin{matrix}0 & 0 & 0 & 0\\0 & 0 & 0 & 0\\0 & 0 & 0.2 & 0\\0 & 0 & 0 & 0\end{matrix}\right]\left[\begin{matrix}x_0\\x_1\\x_2\\x_3\end{matrix}\right]+\left[\begin{matrix}0.47\\-0.235\\-0.65\\0\end{matrix}\right]^T\left[\begin{matrix}x_0\\x_1\\x_2\\x_3\end{matrix}\right]$$
1. $$\left[\begin{matrix}-1.0 & 0 & 0 & 0\\0 & -1.0 & 0 & 0\\0 & 0 & -1.0 & 0\\0 & 0 & 1.0 & 0\\0 & 0 & 0 & 1.0\end{matrix}\right]\left[\begin{matrix}x_{0}\\x_{1}\\x_{2}\\x_{3}\end{matrix}\right]\leq\left[\begin{matrix}0\\0\\0\\0.3443\\0\end{matrix}\right]+\left[\begin{matrix}0\\0\\0\\0\\1.0\end{matrix}\right]\left[\begin{matrix}\theta_{0}\end{matrix}\right]$$
2. $$\left[\begin{matrix}1.0 & -1.0 & -1.0 & 0\\1.0 & -1.0 & 0 & 1.0\end{matrix}\right]\left[\begin{matrix}x_{0}\\x_{1}\\x_{2}\\x_{3}\end{matrix}\right]=\left[\begin{matrix}-0.2735\\0\end{matrix}\right]+\left[\begin{matrix}0\\0\end{matrix}\right]\left[\begin{matrix}\theta_{0}\end{matrix}\right]$$
3. $$\left[\begin{matrix}-1.0\\1.0\end{matrix}\right]\left[\begin{matrix}\theta_{0}\end{matrix}\right]\leq\left[\begin{matrix}0\\1.0\end{matrix}\right]$$
```

Then I used ` solve_mpqp.solve_mpqp(problem, algorithm = solve_mpqp.mpqp_algorithm.combinatorial)` to solve it. But the result showed that there is only one critical region, and the **A** is a zero matrix, **b** is [0, 0, 0.3089, 0] in x(theta) = A@theta + b. Obviously, this answer is wrong. Could you help to find whether there are bugs in ppopt? Thank you a lot!!!!
[model_coeff.zip](https://github.com/TAMUparametric/PPOPT/files/11567308/model_coeff.zip)
![979dc7705b0151383d4446afe05cca8](https://github.com/TAMUparametric/PPOPT/assets/80943977/8da48ee1-08c9-4e31-adaa-3fdd0878e912)
![f6ba7aa6dc03f30c082e078e143a6c0](https://github.com/TAMUparametric/PPOPT/assets/80943977/e44fc239-a5c6-4983-ac6e-c8589d0e3f5a)

**Comment by TimberJ99** [comment]
Further more I notices that the method `ans.verify_solution()` returned `False`. Maybe there is some numeriacal issue?

**Comment by DKenefake** [comment]
Howdy, thank you so much for using the tool and providing the feedback!

I know what is happening here, as the hessian matrix of the objective, Q, is not positive definite then it is not able to invert it to make the explicit solution. 

As it stands, the case of mpQP with only positive semidefinite objective is an underexplored topic in the literature (as it is not as straight forward as the other case). As the 1-1 property of theta to x breaks down, e.g. the solution is not necessarily unique. When looking at the stationarity conditions of the mpQP, we need the inverse of Q to exist to make the 1-1 relationship.

```
Qx + c + A^T\lambda + C^T\mu= 0
```

Would it be possible for you to check what the results are if you add a very small positive value across the diagonal of the matrix?

As of now ppopt does not support the positive semidefinite case, but that will change in the future as we add new algorithms/ideas such as explored in [1].

[1]   P. Tondel, T. A. Johansen and A. Bemporad, "Further results on multiparametric quadratic programming," 42nd IEEE International Conference on Decision and Control (IEEE Cat. No.03CH37475), Maui, HI, USA, 2003, pp. 3173-3178 Vol.3, doi: 10.1109/CDC.2003.1273111.
