### ISSUE TITLE
Toggle for optional pre-processing of constraints in MPModeler

### ISSUE THREAD

**Issue by nchrisandina** [TAMUparametric/PPOPT#44]
**Is your feature request related to a problem? Please describe.**
Sometimes I know all the constraints I'm introducing in MPModeler are non-redundant, but `model.formulate_problem()` does pre-processing by default and that increases runtime unnecessarily.

**Describe the solution you'd like**
A toggle within `formulate_problem()` to make processing constraints optional.

**Comment by DKenefake** [comment]
PR #45 adds this feature, this will be release on the public branch soon.
