### ISSUE TITLE
Mute Warnings

### ISSUE THREAD

**Issue by Wenlong-Codes** [TAMUparametric/PPOPT#62]
Hi, thank you for developing PPOPT!

I found that the warnings raised by the program (mplp_program.py) are not implemented via the warnings library, which cannot be muted and disrupts the progress bar of tqdm. It would be much appreciated if the warnings can be muted. 

Here is one possible solution:

```
import warnings
# grab all warnings
warnings_list = self.warnings()

# print warnings if there are any
if len(warnings_list) > 0:
    for warning_item in warnings_list:
        warnings.warn(warning_item)
```

**Comment by DKenefake** [comment]
Hey, thank you for using PPOPT!

Yes, this makes sense. I will look at implementing that this week.
